/**
* Generated by : Mustafa Sacli
*/
/**
* Dependencies Simple scripts;
* - simplejs.common.1.0.0.js
* -
*/
$(document).ready(function () {
    setTimeout(function () {
        callSimpleAjaxDropDowns();
    }, 500);
});

function loadDropDownWithOps(dropDownId, dropDownUrl, selectedValue, defaultText = "Seçiniz", default_text_value,
    valueProperty = "Value", textProperty = "Text", url_values, error_function, pre_action, post_action) {
    let dropDown = $('#' + dropDownId);

    if (isNotNullAndUndefined(dropDown) === false)
        throw new Error('dropdown element not found.');

    dropDown.empty();

    if (isNotNullAndUndefined(dropDownUrl) === false || isNullOrWhiteSpace(toNullString(dropDownUrl)))
        throw new Error('Ajax request url should be defined.');

    if (isNotNullAndUndefined(textProperty) === false)
        throw new Error('text property for ajax request should be defined.');

    if (isNotNullAndUndefined(valueProperty) === false)
        throw new Error('value property for ajax request should be defined.');

    if (isNullOrWhiteSpace(defaultText) === false || isNullOrWhiteSpace(toNullString(default_text_value)) === false) {
        dropDown.append($('<option></option>')
            .attr('value', toNullString(default_text_value))
            .text(toNullString(defaultText)));
    }

    try {
        if (isNotNullAndUndefined(pre_action) && isNullOrWhiteSpace(toNullString(pre_action)) === false) {
            pre_action();
        }
    } catch (err) {
        console.error(err);
    }

    $.getJSON(dropDownUrl, url_values, function (response) {
        $.each(response, function (key, entry) {
            // debugger;
            dropDown.append($('<option></option>')
                .attr('value', entry[valueProperty])
                .text(entry[textProperty]));
        });
    }).done(function () {
        try {
            // debugger;
            if (isNotNullAndUndefined(selectedValue) && isNullOrWhiteSpace(toNullString(selectedValue)) === false) {
                setTimeout(function () {
                    // debugger;
                    dropDown.val(selectedValue);
                    //if (toNullString(dropDown.val()) !== toNullString(selectedValue)) {
                    //}
                }, 10);
            } else {
                dropDown.prop('selectedIndex', 0);
            }
            // console.log(selectedValue);
            triggerComponent('#' + dropDownId, 'change');
        } catch (err) {
            console.error(err);
        }

        try {
            // debugger;
            if (isNotNullAndUndefined(post_action) && isNullOrWhiteSpace(toNullString(post_action)) === false) {
                post_action();
            }
        } catch (err) {
            console.error(err);
        }
    }).fail(function () {
        if (isNotNullAndUndefined(error_function)) {
            error_function();
        }
    });
}

/*
 TODO : SHOULD BE TESTED.
 */
function callSimpleAjaxDropDowns() {
    // debugger;
    $.each($(".simple-ajax-call"), function (key, entry) {
        rebuildDropDown(entry);
    });
}

function rebuildDropDown(dropdownElement) {
    try {
        // debugger;
        /**
         * <div class="col-md-4">
            <div class="form-group form-md-line-input form-md-floating-label">
                <label for="dropDownId" class="control-label">Choice: </label>
                <select id="dropDownId" class="form-control select2 tooltips simple-ajax-call"
                action_url="" text_item="" value_item="" default_value="" default_value_function="" default_text="" default_text_value=""
                value_dictionary_function="" error_function="" pre_action="" post_action=""></select>
            </div>
        </div>
         **/
        // ajax call and build drop down.

        let action_url_value = dropdownElement.getAttribute('action_url');
        let text_item_value = dropdownElement.getAttribute('text_item');
        let value_item_value = dropdownElement.getAttribute('value_item');
        let default_value = dropdownElement.getAttribute('default_value');
        let default_value_function = dropdownElement.getAttribute('default_value_function');
        let default_text = toNullString(dropdownElement.getAttribute('default_text'));
        let default_text_value = toNullString(dropdownElement.getAttribute('default_text_value'));
        let value_dictionary_function = dropdownElement.getAttribute('value_dictionary_function');
        let error_function = dropdownElement.getAttribute('error_function');
        let values = null;
        let pre_action = dropdownElement.getAttribute('pre_action');
        let post_action = dropdownElement.getAttribute('post_action');

        if (isNotNullAndUndefined(value_dictionary_function) && isNullOrWhiteSpace(toNullString(value_dictionary_function)) === false) {
            values = window[value_dictionary_function]();
        }
        let def_value = null;

        try {
            if (isNotNullAndUndefined(default_value_function) && isNullOrWhiteSpace(toNullString(default_value_function)) === false) {
                def_value = window[default_value_function]();
            }
        } catch (err2) {
            console.error(err2);
        }

        if (isNotNullAndUndefined(def_value) === false && isNullOrWhiteSpace(toNullString(default_value)) === false) {
            def_value = toNullString(default_value);
        }

        loadDropDownWithOps(
            dropdownElement.id, action_url_value, def_value, toNullString(default_text), default_text_value,
            value_item_value, text_item_value, values, function () {
                console.log('Error at loading drop down with ' + dropdownElement.id + ' id.');

                if (isNotNullAndUndefined(error_function) && isNullOrWhiteSpace(toNullString(error_function)) === false) {
                    window[error_function]();
                }
            }, pre_action, post_action);
    } catch (err) {
        console.error(err);
    }
}

/*
 Using;
        <div class="col-md-4">
            <div class="form-group form-md-line-input form-md-floating-label">
                <label for="VergiDairesiId2" class="control-label">Vergi Dairesi: </label>
                <select id="VergiDairesiId2" class="form-control select2 tooltips simple-ajax-call"
                        action_url="@vergiDairesiListeUrl" text_item="Text" value_item="Value" default_value="@Model.VergiDairesiId" default_value_function="" default_text="Seçiniz"
                        default_text_value="" value_dictionary_function="" error_function="" pre_action="" post_action=""></select>
            </div>
        </div>

<script src="~/Scripts/simplejs.common.1.0.0.js" type="text/javascript"></script>
<script src="~/Scripts/simplejs.component.1.0.0.js" type="text/javascript"></script>
<script src="~/Scripts/simplejs.dropdown.1.0.0.js" type="text/javascript"></script>
 */