/**
* Generated by : Mustafa Sacli
*/
/**
* Dependencies Simple scripts;
* -
* -
*/
$(document).ready(function () {
});

function isEmptyOrSpaces(str) {
    return str === null || str.match(/^ *$/) !== null;
}

function isNullOrWhiteSpace(value) {
    var result = true;
    if (isNotNullAndUndefined(value) === false) {
        return result;
    }
    if (value.length === 0) {
        return result;
    }
    var temp = value;
    temp = temp.trim();
    if (temp.length === 0) {
        return result;
    }

    result = false;
    return result;
}

function isNotNullAndUndefined(data) {
    var result = false;
    result = data !== null && data !== undefined;
    return result;
}

function toNullString(data) {
    var result = '';
    if (isNotNullAndUndefined(data)) {
        result = data.toString();
    }

    return result;
}

function toStringWithDefault(data, defaultValue = null) {
    var result = '';
    if (isNotNullAndUndefined(data)) {
        result = data.toString();
    } else if (isNotNullAndUndefined(defaultValue)) {
        result = toNullString(defaultValue);
    }

    return result;
}

function encodeAsHtml(controlId) {
    var ctrl = $(controlId);
    var returnValue = '';
    if (isNotNullAndUndefined(ctrl)) {
        var value = $(controlId).val();
        if (isNotNullAndUndefined(value)) {
            value = $('<div>').text(value).html();
            return value;
        }
    }

    return returnValue;
}

function encodeText(value) {
    var returnValue = '';
    if (isNotNullAndUndefined(value)) {
        returnValue = encodeURIComponent(value);
    }

    return returnValue;
}
